codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: auto
      sql:
        target: 100%    # the required coverage value
        threshold: 1%  # the leniency in hitting the target
        flags:
          - sql
          - unittests
      sql-jdbc:
        target: 50%    # the required coverage value
        threshold: 1%  # the leniency in hitting the target
        flags:
          - sql-jdbc
          - unittests
